### ISSUE TITLE
Does not work with grafana version 9.4.7

### ISSUE THREAD

**Issue by ginesgb** [Checkmk/grafana-checkmk-datasource#195]
Hi, I have installed it on Grafana 9.4.7 and it is not able to perform the host query, I attach the screenshot, therefore it cannot extract information.
What data should I modify? Best regards
![2023_05_16_11_04_59_Explore_Checkmk_Grafana](https://github.com/Checkmk/grafana-checkmk-datasource/assets/4158441/b1139a53-d1dc-47a7-be90-b7bcbec9cd87)
![2023_05_16_11_03_22_Checkmk_Data_sources_Configuration_Grafana](https://github.com/Checkmk/grafana-checkmk-datasource/assets/4158441/4d6a16ca-7822-4439-b5e9-e3437132b410)

**Comment by TheSpacyCat** [comment]
Hi!

The suggestions are filtered based on what is already present in the other fields. Do you have any hosts with the tags you selected?

**Comment by ginesgb** [comment]
Hello, I have already seen my error, it is the role of the Grafana user that must be the same as the automation one, I just read it from another user that you have posted here in his answer and now it works, thank you very much. All the best

**Comment by TheSpacyCat** [comment]
Great, good that your issue is solved.

The current version of the plugin is supposed to check for that when you configure the datasource. Could you tell me which version you are using? I'll write it down as a bug in case it is the latest one.
