### ISSUE TITLE
Alias for the new V3.x in Grafana

### ISSUE THREAD

**Issue by DM-LUKAD** [Checkmk/grafana-checkmk-datasource#211]
Hello, 
first: thank you for this great plugin! Its working very well so far.
Im using Check MK V2.2.0p3 and Grafana 10.0.0 at the moment.
All fine, but there are some Grafana-plugins, that needs an alias for some metics.
Otherwise the plugins can not "address" the different metric. 
(OK mal kurz in deutsch...) 
Wenn ich z.B. in einem Plugin zwei Interfaces nach der Bandbreite abfrage, wird der Name
der Mertic "Single metric" sein (siehe Screenshot). 
Das passiert z.B. beim Visuplugin "Diagram". Dann sind ja zwei Metiken mit dem selben Namen aktiv und es funktioniert nicht.
Könnte man nun noch einen "Alias" als Namen nehmen, wäre das sehr einfach. Ich hoffe ihr versteht mich.

VIELEN DANK!!!

![screen1](https://github.com/Checkmk/grafana-checkmk-datasource/assets/47664571/b4d45e85-856a-4a02-bac2-ff9395f78a9f)
![screen2](https://github.com/Checkmk/grafana-checkmk-datasource/assets/47664571/1f7e4da2-add7-4be8-b352-ec7322681077)

**Comment by BenediktSeidl** [comment]
Thanks for the input. We are aware of the situation, it is tracked in #60 
Sadly I don't have information when we will be able to implement this.
