### ISSUE TITLE
Hostname as fieldname not possible anymore

### ISSUE THREAD

**Issue by swgATpj** [Checkmk/grafana-checkmk-datasource#238]
After I have updated the checkmk plugin from (I'm not sure exactly) version 2 to version 3.1.1 I can not set the fieldname to the hostname. On the old version I could set the label of each query to the hostname, f.e. with _$host_.

**Comment by BenediktSeidl** [comment]
can you roll back to a 2.X version and show me some screenshots of your query configuration? i don't understand what you were doing.

**Comment by swgATpj** [comment]
> can you roll back to a 2.X version and show me some screenshots of your query configuration? i don't understand what you were doing.
It's the 'label-format' there. I have also seen on the panel-json that there is something like this already set: `"format": "$host",`, but it doesn't work - it shows the service-name 'Uptime'.
![checkmk_custom_label](https://github.com/Checkmk/grafana-checkmk-datasource/assets/104566558/5fe6c8d1-55f8-45b1-9e59-532c20e5359d)

**Comment by BenediktSeidl** [comment]
Thanks for the additional information, I was not aware that we had a "Label Format" Field in the 2.X versions of this plugin.

In the meantime we released 3.2.2 which added a "Custom label" field to the query:

![2024-02-29_09-43](https://github.com/Checkmk/grafana-checkmk-datasource/assets/1055738/08679613-a869-49db-9f13-4475833d6767)

Can you update to 3.2.2 and give it a try?

**Comment by swgATpj** [comment]
Yes, it works now again. Thanks!
