### ISSUE TITLE
Grafana 11.3 dashboard variable is always $undefined

### ISSUE THREAD

**Issue by GunFood** [Checkmk/grafana-checkmk-datasource#278]
Hi,

with update to Grafana 11.3 dashboard variables are always $undefined then using checkmk-datasource. The same can be reconstructed in  Grafana cloud.

![grafana_variable available](https://github.com/user-attachments/assets/067ff173-9096-437c-9db0-a80df3ecc634)
![grafana_variable not available](https://github.com/user-attachments/assets/32fce8ed-5ebe-4dc0-bac1-4afb083629aa)

Reply from Grafana support:
After reviewing the matter, our team has confirmed that this appears to be related to the Checkmk plugin and how it handles variables. Since this plugin is developed and maintained by Checkmk GmbH, the best course of action would be to reach out directly to the plugin developers for further assistance.

**Comment by lpetrora** [comment]
Hi GunFood, can you tell me in which Checkmk and plugin versions are you experiencing this issue? 
Thanks in advance,

**Comment by GunFood** [comment]
checkmk 2.2.0p35 and datasource plugin 3.4.0 (was the same with 3.3.0)

**Comment by lpetrora** [comment]
Thanks for the report. We were able to reproduce and fix the issue
