### ISSUE TITLE
Datasource not offering any Site/Hosts/Services

### ISSUE THREAD

**Issue by Blogshot** [Checkmk/grafana-checkmk-datasource#36]
Our installation:
- CheckMK Enterprise in Version 1.6.0p11
- Grafana v7.3.1
- CheckMK Plugin v1.1.0

Grafana is running via docker:
```
docker run \
 -d \
 -p 8443:3000 \
 --name grafana \
 --restart always \
 --env "GF_AUTH_ANONYMOUS_ENABLED=true" \
 --env "GF_INSTALL_PLUGINS=https://github.com/tribe29/grafana-checkmk-datasource/archive/1.1.0.zip;checkmk-datasource" \
 --env "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=checkmk-datasource" \
 -v /opt/grafana_data:/var/lib/grafana \
 grafana/grafana
``` 

When configuring the plugin, it is shown with a red "unsigned"-badge. Aside from that it accepts my credentials for CheckMK and shows `Datasource is working` when saving.

However, when creating a new panel there are no sites,  hosts or services being offered after selecting "CheckMK" as datasource. The CheckMK user for the login had access to around 8-9 machines before switching to an automation password.

Update: This is a permission issue. When using an administrator account, the Hosts become selectable. There is no mention of any required permissions as far as I can see. What permissions are needed?

**Comment by gurubert** [comment]
Administrator permissions are need to read all hosts from WATO.

**Comment by lucianpatian** [comment]
how do you send the URL and USER/PASS values as env_vars? I'm trying to add these using helm deployment, the installation of the plugin works but i'm having trouble in assigning the 3 needed values as env_vars.

thanks!

**Comment by Blogshot** [comment]
@lucianpatian I feel like your question should be in an issue on its own.

Personally, I didn't give USER/PASS via env, but configured them once. The volume takes ensures my configuration stays persistent.

**Comment by lucianpatian** [comment]
i actually didn't open an issue because i was just asking for an advice and found this as closest to it. basically i'm trying to automate the entire plugin installation via helm charts, i was able to install it but i'm having trouble in sending the URL and API credentials as env_vars.

cheers!
