### ISSUE TITLE
Fetch error: 404 Not Found Instantiating

### ISSUE THREAD

**Issue by JulianeKrone** [Checkmk/grafana-checkmk-datasource#53]
Hello,

After integrating the plugin, I get the following error message on Grafana:

"Fetch error: 404 Not Found Instantiating http://localhost:3000/public/app/plugins/datasource/dist/module Loading app/plugins/datasource/dist/module"

Have tried every version of Grafana and the plugins but always the same. Does anyone happen to know what could be causing this?

**Comment by BenediktSeidl** [comment]
Please try again with the current stable version of grafana and the main branch of this git repository.
How exactly do you install the plugin? Are there any errors in the grafana log? You should at least see a line like that:
```
logger=plugin.manager t=2022-04-19T07:47:10.06+0000 lvl=info msg="Plugin registered" pluginId=tribe-29-checkmk-datasource
```
